### ISSUE TITLE
Excel Calculator

### ISSUE THREAD

**Issue by bentron2000** [coreypkolb/Krooshnof-UV-Enlarger#1]
Hi there, 

Are there plans to update this repo with the calculator? :)

Any information hugely appreciated - I'm embarking on a huge UV enlarger project :)

Can contribute wisdom as I gain it

Cheers

B

**Comment by coreypkolb** [comment]
I have dropped the calculator in. I will update the read me with instructions. The short of it is you need to plug in your print size and negative size to figure out the geometry and focal lengths for the enlarger.

**Comment by dkrooshof** [comment]
Hi Ben, with most builders I do a video call to talk through the pitfalls of building a UV enlarger, let me know if you'd like that. Cheers, Douwe

**Comment by bentron2000** [comment]
> Hi Ben, with most builders I do a video call to talk through the pitfalls of building a UV enlarger, let me know if you'd like that. Cheers, Douwe

Would very much like to do that :) Thank you :)  I'll DM via your instagram :)
